version: "3"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'lacosina'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '2012:3306'
    expose:
      - '3306'
